version: '2.1'
services:
  apollo_server_go:
    container_name: apollo_server_go
    hostname: apollo_server_go
    build: .
    volumes:
      - "./config.json:/config.json"
    working_dir: /app
    environment:
      - GIN_MODE=release
    ports:
      - "8070:80"
    network_mode: bridge
